---
permalink: install/concept_spare_core_array_lun_requirement_for_core_dumps.html 
sidebar: sidebar 
keywords: spare, array, lun, requirement, core, dumps 
summary: Para sistemas ONTAP independentes e nós em pares de HA, é necessário criar um LUN de array sobressalente de tamanho adequado para manter os despejos de núcleo se não houver disco sobressalente disponível. 
---
= Requisito de LUN de matriz sobressalente para despejos de núcleo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para sistemas ONTAP independentes e nós em pares de HA, é necessário criar um LUN de array sobressalente de tamanho adequado para manter os despejos de núcleo se não houver disco sobressalente disponível.

Em um sistema que usa discos e LUNs de array, um LUN de array sobressalente não é necessário para um despejo de núcleo se um disco sobressalente estiver disponível. Se nem um LUN de matriz sobressalente nem um disco sobressalente estiverem disponíveis, não haverá lugar para o núcleo ser despejado.

Um despejo de memória contém o conteúdo de memória e NVRAM. Durante um pânico do sistema, o ONTAP despeja o núcleo para um LUN de matriz sobressalente ou disco sobressalente, se existir um sobressalente. Após a reinicialização, o núcleo é lido do sobressalente e salvo em um despejo de núcleo no sistema de arquivos raiz. O suporte técnico pode então usar o despejo de memória para ajudar a solucionar o problema.

O _Hardware Universe_ contém o tamanho mínimo de LUN de matriz de núcleo sobressalente para cada plataforma.

*Informações relacionadas*

https://hwu.netapp.com["NetApp Hardware Universe"]
