---
permalink: install/concept_back_end_configuration_errors_detected_by_ontap_commands.html 
sidebar: sidebar 
keywords: back-end, configuration, errors, detected, ontap, commands, output, examples 
summary: O comando storage errors show fornece detalhes, no nível de LUN do array, sobre erros comuns de configuração back-end. Você também pode usar os comandos show de erro de disco de armazenamento e show de disco de armazenamento -errors para exibir os erros. 
---
= Erros de configuração de back-end detetados pelos comandos ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O `storage errors show` comando fornece detalhes, no nível de LUN de array, sobre erros comuns de configuração back-end. Também pode utilizar os `storage disk error show` comandos e `storage disk show -errors` para visualizar os erros.

Você deve corrigir os erros de configuração de back-end identificados por esses comandos antes de configurar o ONTAP para funcionar com LUNs de array.

[NOTE]
====
Embora o `storage errors show` comando forneça detalhes de erro relativos apenas a LUNs de array, os `storage disk error show` comandos e `storage disk show -errors` podem fornecer detalhes de erro relacionados a LUNs de array, bem como discos.

====
Quando há um erro de configuração de back-end que impede que os dispositivos em sua configuração funcionem juntos, o `storage array config show` comando instrui você a executar erros de armazenamento show para obter os detalhes do erro.



== Lista de erros de configuração de back-end

Os `storage errors show` comandos , `storage disk error show` e `storage disk show -errors` podem ajudar a identificar erros de configuração de back-end, como os seguintes:

* Há menos de dois caminhos para um LUN de array.
* Todos os caminhos para um LUN de array são para o mesmo controlador de storage array.
* Dois LUNs de array são apresentados com o mesmo ID de LUN.
* As IDs de LUN para o mesmo LDEV não correspondem em todas as portas de destino sobre as quais o LDEV será visível.
* O LUN de array excede o tamanho máximo de LUN do ONTAP.
* O LUN de array não atende ao tamanho mínimo de LUN do ONTAP.
* O tamanho do bloco de um LUN de matriz é inválido.
* Um LUN de acesso é apresentado ao ONTAP.




== Exemplos de saída que mostram os erros de configuração de back-end

A `storage errors show` saída é agrupada por storage array (se houver mais de um storage array por trás do sistema ONTAP). O nome e identificador exclusivo (UID) de um LUN de array são mostrados, quando aplicável.

O exemplo de saída a seguir mostra um tipo de erro - apenas um caminho para um LUN de matriz. Isso é um erro porque o ONTAP requer dois caminhos para um LUN de array.

[NOTE]
====
Quatro caminhos para um LUN de array são suportados para configurações em cluster.

====
O exemplo a seguir mostra os erros retornados pelo `storage errors show` comando por causa de apenas um único caminho configurado para um LUN de matriz:

[listing]
----

systemf47ab::*> storage errors show
DGC-1.51         onepath           DGC-1.51 (6006016044d03500ae553e55b09fe311): This array LUN is only available on one path. Proper configuration requires two paths.
DGC-1.54         onepath           DGC-1.54 (6006016044d03500b4553e55b09fe311): This array LUN is only available on one path. Proper configuration requires two paths.
DGC-1.55         onepath           DGC-1.55 (6006016044d03500b6553e55b09fe311): This array LUN is only available on one path. Proper configuration requires two paths.
DGC-1.56         onepath           DGC-1.56 (6006016044d03500b8553e55b09fe311): This array LUN is only available on one path. Proper configuration requires two paths.
DGC-1.57         onepath           DGC-1.57 (6006016044d03500ba553e55b09fe311): This array LUN is only available on one path. Proper configuration requires two paths.
DGC-1.58         onepath           DGC-1.58 (6006016044d03500bc553e55b09fe311): This array LUN is only available on one path. Proper configuration requires two paths.
----
O exemplo a seguir mostra erros semelhantes retornados pelo `storage disk show -errors` comando:

[listing]
----

systemf47ab::*> storage disk show -errors
DGC-1.2          onepath           DGC-1.2 (6006016044d03500e0720e22b59fe311): This array LUN is only available on one path. Proper configuration requires two paths.
DGC-1.3          onepath           DGC-1.3 (6006016044d03500e2720e22b59fe311): This array LUN is only available on one path. Proper configuration requires two paths.
DGC-1.4          onepath           DGC-1.4 (6006016044d03500e3720e22b59fe311): This array LUN is only available on one path. Proper configuration requires two paths.
DGC-1.5          onepath           DGC-1.5 (6006016044d03500e4720e22b59fe311): This array LUN is only available on one path. Proper configuration requires two paths.
DGC-1.6          onepath           DGC-1.6 (6006016044d03500e5720e22b59fe311): This array LUN is only available on one path. Proper configuration requires two paths.
DGC-1.7          onepath           DGC-1.7 (6006016044d03500e6720e22b59fe311): This array LUN is only available on one path. Proper configuration requires two paths.
----