---
permalink: install/concept_using_lun_groups_to_partition_the_load_over_v_series_connections.html 
sidebar: sidebar 
keywords: benefits, use, multiple, lun, groups 
summary: Você pode usar vários grupos de LUN na configuração de storage para obter capacidade adicional e melhorar a performance do sistema, espalhando o workload por mais portas de destino. 
---
= Benefícios do uso de vários grupos LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar vários grupos de LUN na configuração de storage para obter capacidade adicional e melhorar a performance do sistema, espalhando o workload por mais portas de destino.

Um _LUN group_ é um conjunto de dispositivos lógicos na matriz de armazenamento que um sistema ONTAP acessa pelos mesmos caminhos. O administrador da matriz de armazenamento configura um conjunto de dispositivos lógicos como um grupo para definir quais WWPNs de host podem acessá-los. ONTAP refere-se a este conjunto de dispositivos como um _grupo LUN_.

Os benefícios de usar vários grupos LUN são os seguintes:

* Há limites para o número de LUNs compatíveis com um determinado par de portas de iniciador de FC.
+
Em particular, para grandes matrizes de armazenamento, a capacidade necessária pode exceder o que um único grupo LUN pode fornecer. Portanto, usar vários grupos LUN pode ser benéfico.

* Você pode particionar a carga de LUNs de array nos pares de portas do iniciador FC.


[NOTE]
====
O uso de vários grupos de LUN não é compatível com todos os storages de armazenamento. Consulte a _Interoperability Matrix_ para determinar se uma configuração usando vários grupos LUN é suportada para seu storage array.

====
*Informações relacionadas*

https://mysupport.netapp.com/matrix["Ferramenta de Matriz de interoperabilidade do NetApp"]
