---
permalink: install/reference_the_storage_errors_show_messages_and_their_resolution.html 
sidebar: sidebar 
keywords: storage, errors, show, messages, resolution 
summary: Quando os erros de armazenamento mostram sinaliza uma condição de erro, você precisa determinar por que o erro ocorreu e como corrigi-lo. 
---
= Os erros de armazenamento mostram mensagens e sua resolução
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
 `storage errors show`Quando sinaliza uma condição de erro, você precisa determinar por que o erro ocorreu e como corrigi-lo.

A tabela a seguir lista os erros de configuração de back-end detetados pelo `storage errors show` e o refere a informações detalhadas sobre as causas de cada erro e sua resolução.

|===
| `storage errors show` mensagem | Para obter mais informações sobre esta mensagem, consulte... 


 a| 
`NAME (Serial #): All paths to this array LUN are connected to the same fault domain. This is a single point of failure``.
 a| 
xref:reference_all_paths_to_an_array_lun_are_on_the_same_storage_array_controller.adoc[Todos os caminhos para um LUN de array estão no mesmo controlador de storage array]



 a| 
`NAME (Serial #), port WWPN1: LUN 1 occurs more than once. LUNs cannot be reused on the same array target port`.
 a| 
xref:reference_duplicate_lun_ids_on_a_target_port.adoc[IDs de LUN duplicados em uma porta de destino]



 a| 
`NAME (Serial #): This array LUN is an access control LUN. It is not supported and should be masked off or disabled``.
 a| 
xref:reference_an_access_control_lun_is_presented_to_ontap.adoc[O LUN de controle de acesso foi apresentado]



 a| 
`NAME (Serial #) This array LUN is configured with conflicting failover modes. Each path to this LUN must use the same mode`.
 a| 
xref:reference_array_luns_are_configured_with_conflicting_failover_modes_clustered_data_ontap_8_2_and_later.adoc[Os LUNs de array são configurados com modos de failover conflitantes]



 a| 
`NAME (Serial #): This Array LUN is only available on one path. Proper configuration requires two paths`.
 a| 
xref:reference_fewer_than_two_paths_to_an_array_lun.adoc[Menos de dois caminhos para um LUN de array]



 a| 
`NAME (Serial #): This array LUN is too large and is not usable. The maximum array LUN size supported is xTB`.
 a| 
xref:reference_array_lun_is_either_smaller_or_larger_than_the_supported_values.adoc[O LUN de array é muito pequeno ou muito grande]



 a| 
`NAME (Serial #): This array LUN is too small and is not usable. The minimum array LUN size supported is 1GB`.
 a| 
xref:reference_array_lun_is_either_smaller_or_larger_than_the_supported_values.adoc[O LUN de array é muito pequeno ou muito grande]



 a| 
`NAME (Serial #): This Array LUN is using multiple LUN IDs. Only one LUN ID per serial number is supported`.
 a| 
xref:reference_lun_ids_for_the_same_ldev_do_not_match.adoc[As IDs de LUN para o mesmo LDEV não correspondem]

O endereçamento do conjunto de volume é inconsistente



 a| 
`NAME (Serial #): This array LUN is marked foreign and has a reservation`.
 a| 
xref:reference_array_lun_is_marked_foreign_and_has_a_reservation_data_ontap_8_3_and_later.adoc[Array LUN é marcado como estrangeiro e tem uma reserva]

|===