---
permalink: install/task_preparing_a_storage_array_for_use_with_ontap_systems.html 
sidebar: sidebar 
keywords: prepare, storage, array, use, ontap, systems 
summary: Antes de começar a configurar sistemas ONTAP em uma configuração com LUNs de array, o administrador do storage deve preparar o armazenamento para uso com o ONTAP. 
---
= Preparação de um storage array para uso com sistemas ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de começar a configurar sistemas ONTAP em uma configuração com LUNs de array, o administrador do storage deve preparar o armazenamento para uso com o ONTAP.

*O que você vai precisar*

As matrizes de armazenamento, firmware e comutadores que pretende utilizar na configuração têm de ser suportadas pela versão específica do ONTAP.

* https://mysupport.netapp.com/NOW/products/interoperability["Interoperabilidade do NetApp"]
+
No IMT, você pode usar o campo solução de armazenamento para selecionar sua solução MetroCluster. Use o *Explorador de componentes* para selecionar os componentes e a versão do ONTAP para refinar sua pesquisa. Você pode clicar em *Mostrar resultados* para exibir a lista de configurações compatíveis que correspondem aos critérios.

* https://hwu.netapp.com["NetApp Hardware Universe"]


Você deve coordenar com o administrador do storage array para executar essa tarefa no storage array.

.Passos
. Crie pelo menos quatro LUNs no storage array para que os sistemas ONTAP usem.
+
Cada nó no par de HA requer um LUN de array para o volume raiz e um LUN de array para despejos centrais.

. Configure parâmetros no storage array que são necessários para trabalhar com o ONTAP.
+
** https://docs.netapp.com/us-en/ontap-flexarray/implement-third-party/index.html["Implementação de virtualização de FlexArray para storage de terceiros"]
** https://docs.netapp.com/us-en/ontap-flexarray/implement-e-series/index.html["Implementação de virtualização FlexArray para storage NetApp e-Series"]



