---
permalink: install/task_verifying_if_the_back_end_configuration_matches_the_expected_output.html 
sidebar: sidebar 
keywords: verify, back-end, configuration, matches, intended, configuration 
summary: Depois de resolver os erros de configuração de back-end detetados pelos erros de armazenamento mostrados, você deve verificar se a configuração de back-end existente corresponde à configuração desejada e corrigir problemas decorrentes de qualquer incompatibilidade. 
---
= Verificar se a configuração de back-end corresponde à configuração pretendida
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depois de resolver os erros de configuração de back-end detetados pelo `storage errors show`, você deve verificar se a configuração de back-end existente corresponde à configuração pretendida e corrigir problemas decorrentes de qualquer incompatibilidade.

.Passos
. Introduza o seguinte comando: `storage array config show`
+
A `storage array config show` saída agrupa informações sobre grupos de LUN, contagens de LUN e caminhos por matriz de armazenamento, como mostra o exemplo a seguir para um par de HA:

+
[listing]
----

mysystem1::> storage array config show
             LUN   LUN
Node         Group Count  Array Name      Array Target Port   Initiator
------------ ----- ----- ---------------  ------------------  ---------
mysystem1a    0    10     DGC_RAID5_1      5005076303030124       1a
                                           5005076303088124       1b
                                           5005076303130124       1c
                                           5005076303188124       1d
mysystem1b    0    10     DGC_RAID5_1      5005076303030124       1a
                                           5005076303088124       1b
                                           5005076303130124       1c
                                           5005076303188124       1d
8 entries were displayed.
----
. Verifique a `storage array config show` saída de cada declaração de problema na tabela a seguir e consulte as informações apropriadas para obter a solução.
+
|===
| Se você encontrar este problema... | Veja esta informação... 


 a| 
Grupos LUN vazios
 a| 
xref:reference_reasons_for_no_luns_in_the_array_lun_group.adoc[Motivos para não haver LUNs no grupo LUN de array]



 a| 
Matrizes de armazenamento esperadas em falta
 a| 
xref:reference_reasons_storage_arrays_are_missing_from_command_output.adoc[Motivos pelos quais você pode não ver todos os storages de armazenamento esperados]



 a| 
Mais grupos de LUN de array do que o esperado
 a| 
xref:reference_reasons_for_more_array_lun_groups_than_expected.adoc[Razões para mais grupos LUN de array do que o esperado]



 a| 
Menos grupos de LUN de array do que o esperado
 a| 
xref:reference_reasons_for_fewer_array_lun_groups_than_expected.adoc[Razões para menos grupos de LUN de array do que o esperado]



 a| 
Os grupos LUN de array não mostram o número de LUNs esperados
 a| 
xref:reference_reasons_for_the_incorrect_number_of_luns_in_array_lun_groups.adoc[Razões para o número incorreto de LUNs em grupos LUN de matriz]



 a| 
Menos caminhos do que o esperado
 a| 
xref:reference_fewer_than_two_paths_to_an_array_lun.adoc[Menos de dois caminhos para um LUN de array]



 a| 
Mais caminhos do que o esperado
 a| 
xref:reference_reasons_for_more_paths_to_an_array_lun_than_expected.adoc[Razões para mais caminhos para um LUN de array do que o esperado]

|===

