---
permalink: implement-third-party/concept_ibm_ds_storage_array_families.html 
sidebar: sidebar 
keywords: ibm ds, storage, array, families 
summary: O ONTAP não oferece suporte à combinação de alguns tipos de storage em agregados. Para ajudar você a determinar os LUNs do array que podem ser misturados em um agregado, os storage arrays de cada fornecedor são agrupados em famílias. Ao criar agregados, não é possível misturar LUNs de array de diferentes fornecedores e de diferentes famílias de storage no mesmo agregado. 
---
= Famílias de storage array IBM DS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O ONTAP não oferece suporte à combinação de alguns tipos de storage em agregados. Para ajudar você a determinar os LUNs do array que podem ser misturados em um agregado, os storage arrays de cada fornecedor são agrupados em famílias. Ao criar agregados, não é possível misturar LUNs de array de diferentes fornecedores e de diferentes famílias de storage no mesmo agregado.

Os storage arrays da mesma família compartilham as mesmas características de performance e failover. Por exemplo, todos os membros da mesma família executam failover ativo-ativo ou todos executam failover ativo-passivo. Mais de um fator pode ser usado para determinar famílias de storage array. Por exemplo, matrizes de armazenamento com arquiteturas diferentes estariam em famílias diferentes, embora outras caraterísticas possam ser as mesmas.

A lista a seguir mostra arrays organizados por família:

* Família 1
+
** DS8300
** DS8100


* Família 2
+
** DS8800
** DS8700
** DS8870




A Matriz de interoperabilidade é a autoridade final para obter informações sobre as matrizes de armazenamento suportadas por cada fornecedor.
