---
permalink: implement-third-party/concept_3par_storage_array_families.html 
sidebar: sidebar 
keywords: 3par, storage, array, families 
summary: O ONTAP não oferece suporte à combinação de alguns tipos de storage em agregados. Para ajudar você a determinar os LUNs do array que podem ser misturados em um agregado, os storage arrays de cada fornecedor são agrupados em famílias. Ao criar agregados, não é possível misturar LUNs de array de diferentes fornecedores e de diferentes famílias de storage no mesmo agregado. 
---
= 3PAR famílias de storage array
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O ONTAP não oferece suporte à combinação de alguns tipos de storage em agregados. Para ajudar você a determinar os LUNs do array que podem ser misturados em um agregado, os storage arrays de cada fornecedor são agrupados em famílias. Ao criar agregados, não é possível misturar LUNs de array de diferentes fornecedores e de diferentes famílias de storage no mesmo agregado.

Os storage arrays da mesma família compartilham as mesmas características de performance e failover. Por exemplo, todos os membros da mesma família executam failover ativo-ativo ou todos executam failover ativo-passivo. Mais de um fator pode ser usado para determinar famílias de storage array. Por exemplo, matrizes de armazenamento com arquiteturas diferentes estariam em famílias diferentes, embora outras caraterísticas possam ser as mesmas.

A lista a seguir mostra os storages 3PAR compatíveis organizados por diferentes famílias:

* Família 1: 3PAR GB de armazenamento InServ
+
** Tx00


* Família 2: 3PAR GB de armazenamento InServ
+
** Fx00


* Família 3: Armazenamento 3PAR StoreServ
+
** 20000
** 208xx




A Matriz de interoperabilidade é a autoridade final para obter informações sobre as matrizes de armazenamento suportadas por cada fornecedor.

*Informações relacionadas*

https://mysupport.netapp.com/matrix["Ferramenta de Matriz de interoperabilidade do NetApp"]
