---
permalink: implement-third-party/reference_required_parameters_for_hitachi_storage_arrays_with_ontap_systems.html 
sidebar: sidebar 
keywords: required, parameters, hitachi, storage, arrays, ontap, systems, ams, hus, vsp, hus vm, workaround 
summary: Certas configurações de parâmetros são necessárias no storage de armazenamento para que o storage de armazenamento funcione com sucesso com sistemas ONTAP. 
---
= Parâmetros necessários para matrizes de armazenamento Hitachi com sistemas ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Certas configurações de parâmetros são necessárias no storage de armazenamento para que o storage de armazenamento funcione com sucesso com sistemas ONTAP.



== Parâmetros de sistema necessários para matrizes de armazenamento AMS e HUS

Os parâmetros que devem ser definidos estão listados na seguinte tabela:

|===
| Parâmetro | Definição 


 a| 
`Mapping mode`
 a| 
Ativado



 a| 
`Host group security`
 a| 
Ativado



 a| 
`Mode Setting > Common Setting`
 a| 
Modo padrão



 a| 
`Platform`
 a| 
Não especificado



 a| 
`Middleware`
 a| 
Não especificado

|===


== Parâmetros de sistema necessários para matrizes de armazenamento VSP e HUS VM

Os parâmetros que devem ser definidos estão listados na seguinte tabela:

|===
| Parâmetro | Definição 


 a| 
`Host mode`
 a| 
Padrão ou 00



 a| 
`Port security`
 a| 
Ativado



 a| 
[NOTE]
====
Um grupo de host que é separado dos grupos de host padrão deve ser criado para cada par de portas de destino do iniciador.

====
|===
Os parâmetros do storage de armazenamento devem ser definidos e os LUNs devem ser mapeados para os grupos de hosts antes que o switch seja zoneado para conetar o sistema ONTAP à matriz de armazenamento Hitachi.

Se as portas do iniciador ONTAP FC forem zoneadas com as portas de destino da matriz Hitachi antes que os parâmetros da matriz de armazenamento sejam definidos e os LUNs sejam mapeados para os grupos de host, talvez você não consiga ver os LUNs apresentados à interface do ONTAP.

Nesta situação, o ONTAP gera uma das seguintes mensagens EMS:

[listing]
----
[fci.device.login.reject:info] The PLOGI transmitted by port XX was rejected by port_id 0xYYYY with reason code 0x9 'Invalid R_CTL Field', explanation code 0x29 'Insufficient Resources to Support Login'
----
[listing]
----
[fci.device.login.reject:info]: The PLOGI transmitted by port XX was rejected by port_id 0xYYYY with reason code 0x3 'Nx_Port Not Available, Temporary', explanation code 0x29 'Insufficient Resources to Support Login'
----


== Solução alternativa

Se o zoneamento foi configurado antes de definir os parâmetros e mapear os LUNs para os grupos de hosts, você pode resolver o problema de LUNs não serem visíveis executando uma reinicialização de caminho para forçar uma redescoberta dos LUNs de storage mapeados a partir do storage Hitachi. Consulte solução alternativa quando os LUNs não estiverem visíveis com a secção matrizes de armazenamento Hitachi para obter a solução alternativa para este problema.

xref:reference_workaround_when_luns_are_not_visible_with_hitachi_storage_arrays.adoc[Solução alternativa quando os LUNs não são visíveis com matrizes de armazenamento Hitachi]
